# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GraphAnalysis
                                 A QGIS plugin
 This plugin lets you visualize and manipulate spatial graphs.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-25
        copyright            : (C) 2018 by ISTIC
        email                : team.qgis@etudiant.univ-rennes1.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GraphAnalysis class from file GraphAnalysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .graphAnalysis import GraphAnalysis
    return GraphAnalysis(iface)
