# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GraphAnalysisDialog
                                 A QGIS plugin
 This plugin lets you visualize and manipulate spatial graphs.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-25
        git sha              : $Format:%H$
        copyright            : (C) 2018 by ISTIC
        email                : team.qgis@etudiant.univ-rennes1.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os.path

from PyQt5.QtWidgets import QDialog, QFileDialog, QMessageBox
from qgis.core import QgsProject

from .ui_graphAnalysis_dialog_base import Ui_GraphAnalysisDialogBase
from . import utils


class GraphAnalysisDialog(QDialog,Ui_GraphAnalysisDialogBase):

    def __init__(self):
        QDialog.__init__(self)
        self.setupUi(self)

        self.pushButtonBrowse.clicked.connect(self.showBrowserDialog)

    def clear(self):
        self.lineEditGraphPath.setText("")

    def showBrowserDialog(self):
        bDir, found = QgsProject.instance().readEntry(
            utils.SETTINGS_KEY, utils.SETTING_BROWSER_GRAPH_DIR, None)
        if not found:
            bDir = os.path.expanduser("~")

        filepath, _ = QFileDialog.getOpenFileName(
            self, "Select graph", bDir, "Graphs (*.graph *.txt)")

        if filepath:
            self.lineEditGraphPath.setText(filepath)
            bDir, _ = os.path.split(filepath)
            QgsProject.instance().writeEntry(utils.SETTINGS_KEY,
                                             utils.SETTING_BROWSER_GRAPH_DIR,
                                             bDir)

    def accept(self):
        result, message, details = self.validate()
        if result:
            self.done(QDialog.Accepted)
        else:
            msgBox = QMessageBox()
            msgBox.setWindowTitle("Error")
            msgBox.setText(message)
            msgBox.setDetailedText(details)
            msgBox.setStandardButtons(QMessageBox.Ok)
            msgBox.exec_()

    def validate(self):
        result = True
        message = ""
        details = ""

        self.graphPath = self.lineEditGraphPath.text()
        _, extension = os.path.splitext(self.graphPath)
        extension = extension.lower()
        if not os.path.isfile(self.graphPath) or \
                (extension not in [".graph", ".txt"]):
            result = False
            if len(details) > 0:
                details += "\n"
            details += "The path must be a graph file"

        if not result:
            message = "There were errors in the form"

        return result, message, details
