# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphAnalysis_dockwidget_base.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GraphAnalysisDockWidgetBase(object):
    def setupUi(self, GraphAnalysisDockWidgetBase):
        GraphAnalysisDockWidgetBase.setObjectName("GraphAnalysisDockWidgetBase")
        GraphAnalysisDockWidgetBase.resize(400, 456)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectionButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.selectionButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/plugins/graphAnalysis/resources/logo-select.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.selectionButton.setIcon(icon)
        self.selectionButton.setCheckable(True)
        self.selectionButton.setChecked(False)
        self.selectionButton.setObjectName("selectionButton")
        self.horizontalLayout.addWidget(self.selectionButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget = QtWidgets.QTabWidget(self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tbl_NodeAttributes = QtWidgets.QTableWidget(self.tab)
        self.tbl_NodeAttributes.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tbl_NodeAttributes.setObjectName("tbl_NodeAttributes")
        self.tbl_NodeAttributes.setColumnCount(3)
        self.tbl_NodeAttributes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_NodeAttributes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_NodeAttributes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_NodeAttributes.setHorizontalHeaderItem(2, item)

        self.tbl_NodeAttributes.horizontalHeader().setHighlightSections(False)
        self.tbl_NodeAttributes.horizontalHeader().setStretchLastSection(True)
        self.tbl_NodeAttributes.verticalHeader().setVisible(False)
        self.tbl_NodeAttributes.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_5.addWidget(self.tbl_NodeAttributes)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbl_EdgeAttributes = QtWidgets.QTableWidget(self.tab_2)
        self.tbl_EdgeAttributes.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.tbl_EdgeAttributes.setObjectName("tbl_EdgeAttributes")
        self.tbl_EdgeAttributes.setColumnCount(4)
        self.tbl_EdgeAttributes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_EdgeAttributes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_EdgeAttributes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_EdgeAttributes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_EdgeAttributes.setHorizontalHeaderItem(3, item)
        self.tbl_EdgeAttributes.horizontalHeader().setVisible(True)
        self.tbl_EdgeAttributes.horizontalHeader().setHighlightSections(False)
        self.tbl_EdgeAttributes.horizontalHeader().setStretchLastSection(True)
        self.tbl_EdgeAttributes.verticalHeader().setVisible(False)
        self.tbl_EdgeAttributes.verticalHeader().setHighlightSections(False)
        self.horizontalLayout_3.addWidget(self.tbl_EdgeAttributes)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.addNodeButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.addNodeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/plugins/graphAnalysis/resources/Logo-addnodes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addNodeButton.setIcon(icon1)
        self.addNodeButton.setCheckable(True)
        self.addNodeButton.setObjectName("addNodeButton")
        self.horizontalLayout_2.addWidget(self.addNodeButton)
        self.addEdgeButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.addEdgeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/plugins/graphAnalysis/resources/Logo-addedges.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEdgeButton.setIcon(icon2)
        self.addEdgeButton.setObjectName("addEdgeButton")
        self.horizontalLayout_2.addWidget(self.addEdgeButton)
        self.removeNodeButton = QtWidgets.QPushButton(self.dockWidgetContents)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/plugins/graphAnalysis/resources/Logo-deletenodes.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeNodeButton.setIcon(icon3)
        self.removeNodeButton.setObjectName("removeNodeButton")
        self.horizontalLayout_2.addWidget(self.removeNodeButton)
        self.removeEdgeButton = QtWidgets.QPushButton(self.dockWidgetContents)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/plugins/graphAnalysis/resources/Logo-deleteedges.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeEdgeButton.setIcon(icon4)
        self.removeEdgeButton.setObjectName("removeEdgeButton")
        self.horizontalLayout_2.addWidget(self.removeEdgeButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 7, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.addNodeFromLayerButton = QtWidgets.QPushButton(self.dockWidgetContents)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/plugins/graphAnalysis/resources/Logo-addnodes-fromlayer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addNodeFromLayerButton.setIcon(icon5)
        self.addNodeFromLayerButton.setObjectName("addNodeFromLayerButton")
        self.horizontalLayout_6.addWidget(self.addNodeFromLayerButton)
        self.addEdgesFromLayerButton = QtWidgets.QPushButton(self.dockWidgetContents)
        self.addEdgesFromLayerButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/plugins/graphAnalysis/resources/Logo-addedges-fromlayer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addEdgesFromLayerButton.setIcon(icon6)
        self.addEdgesFromLayerButton.setObjectName("addEdgesFromLayerButton")
        self.horizontalLayout_6.addWidget(self.addEdgesFromLayerButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        GraphAnalysisDockWidgetBase.setCentralWidget(self.dockWidgetContents)

        self.retranslateUi(GraphAnalysisDockWidgetBase)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GraphAnalysisDockWidgetBase)

    def retranslateUi(self, GraphAnalysisDockWidgetBase):
        _translate = QtCore.QCoreApplication.translate
        GraphAnalysisDockWidgetBase.setWindowTitle(_translate("GraphAnalysisDockWidgetBase", "Graph layer manager"))
        item = self.tbl_NodeAttributes.horizontalHeaderItem(0)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "Id"))
        item = self.tbl_NodeAttributes.horizontalHeaderItem(1)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "Attribute"))
        item = self.tbl_NodeAttributes.horizontalHeaderItem(2)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("GraphAnalysisDockWidgetBase", "Nodes"))
        item = self.tbl_EdgeAttributes.horizontalHeaderItem(0)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "NodeA"))
        item = self.tbl_EdgeAttributes.horizontalHeaderItem(1)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "NodeB"))
        item = self.tbl_EdgeAttributes.horizontalHeaderItem(2)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "Attribute"))
        item = self.tbl_EdgeAttributes.horizontalHeaderItem(3)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("GraphAnalysisDockWidgetBase", "Edges"))
        self.label.setText(_translate("GraphAnalysisDockWidgetBase", "Simple edition tools"))
        self.label_2.setText(_translate("GraphAnalysisDockWidgetBase", "Add from vector layers"))
