# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphAnalysis_renderer_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GraphAnalysisRendererGuiBase(object):
    def setupUi(self, GraphAnalysisRendererGuiBase):
        GraphAnalysisRendererGuiBase.setObjectName("GraphAnalysisRendererGuiBase")
        GraphAnalysisRendererGuiBase.resize(638, 368)
        self.verticalLayout = QtWidgets.QVBoxLayout(GraphAnalysisRendererGuiBase)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(GraphAnalysisRendererGuiBase)
        self.tabWidget_2.setIconSize(QtCore.QSize(22, 22))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tabWidgetPage1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tabWidgetPage1)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_4.addWidget(self.stackedWidget, 1, 0, 1, 4)
        self.graphicalpropertycombobox = QtWidgets.QComboBox(self.tabWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicalpropertycombobox.sizePolicy().hasHeightForWidth())
        self.graphicalpropertycombobox.setSizePolicy(sizePolicy)
        self.graphicalpropertycombobox.setMinimumSize(QtCore.QSize(0, 26))
        self.graphicalpropertycombobox.setMaximumSize(QtCore.QSize(32767, 22))
        self.graphicalpropertycombobox.setObjectName("graphicalpropertycombobox")
        self.gridLayout_4.addWidget(self.graphicalpropertycombobox, 0, 1, 1, 1)
        self.lblTransparencyPercent = QtWidgets.QLabel(self.tabWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTransparencyPercent.sizePolicy().hasHeightForWidth())
        self.lblTransparencyPercent.setSizePolicy(sizePolicy)
        self.lblTransparencyPercent.setObjectName("lblTransparencyPercent")
        self.gridLayout_4.addWidget(self.lblTransparencyPercent, 0, 2, 1, 1)
        self.legendtypelabel = QtWidgets.QLabel(self.tabWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.legendtypelabel.sizePolicy().hasHeightForWidth())
        self.legendtypelabel.setSizePolicy(sizePolicy)
        self.legendtypelabel.setMaximumSize(QtCore.QSize(32767, 22))
        self.legendtypelabel.setObjectName("legendtypelabel")
        self.gridLayout_4.addWidget(self.legendtypelabel, 0, 0, 1, 1)
        self.sliderTransparency = QtWidgets.QSlider(self.tabWidgetPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderTransparency.sizePolicy().hasHeightForWidth())
        self.sliderTransparency.setSizePolicy(sizePolicy)
        self.sliderTransparency.setMaximum(255)
        self.sliderTransparency.setProperty("value", 0)
        self.sliderTransparency.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTransparency.setObjectName("sliderTransparency")
        self.gridLayout_4.addWidget(self.sliderTransparency, 0, 3, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/themes/default/propertyicons/symbology.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tabWidgetPage1, icon, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tabWidgetPage2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.labelCheckBox = QtWidgets.QCheckBox(self.tabWidgetPage2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCheckBox.sizePolicy().hasHeightForWidth())
        self.labelCheckBox.setSizePolicy(sizePolicy)
        self.labelCheckBox.setObjectName("labelCheckBox")
        self.gridLayout_5.addWidget(self.labelCheckBox, 0, 0, 1, 1)
        self.labelOptionsFrame = QtWidgets.QFrame(self.tabWidgetPage2)
        self.labelOptionsFrame.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOptionsFrame.sizePolicy().hasHeightForWidth())
        self.labelOptionsFrame.setSizePolicy(sizePolicy)
        self.labelOptionsFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelOptionsFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelOptionsFrame.setObjectName("labelOptionsFrame")
        self.gridLayout_5.addWidget(self.labelOptionsFrame, 1, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/themes/default/propertyicons/labels.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tabWidgetPage2, icon1, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tabWidgetPage3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tabWidgetPage3)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.tblNodeAttributes = QtWidgets.QTableWidget(self.tabWidgetPage3)
        self.tblNodeAttributes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblNodeAttributes.setAlternatingRowColors(True)
        self.tblNodeAttributes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblNodeAttributes.setObjectName("tblNodeAttributes")
        self.tblNodeAttributes.setColumnCount(2)
        self.tblNodeAttributes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblNodeAttributes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblNodeAttributes.setHorizontalHeaderItem(1, item)
        self.tblNodeAttributes.horizontalHeader().setVisible(True)
        self.gridLayout_6.addWidget(self.tblNodeAttributes, 1, 0, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.tabWidgetPage3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 8, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_AddEdgeAttribute = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.pushButton_AddEdgeAttribute.setObjectName("pushButton_AddEdgeAttribute")
        self.horizontalLayout.addWidget(self.pushButton_AddEdgeAttribute)
        self.pushButton_AddNodeAttribute = QtWidgets.QPushButton(self.tabWidgetPage3)
        self.pushButton_AddNodeAttribute.setObjectName("pushButton_AddNodeAttribute")
        self.horizontalLayout.addWidget(self.pushButton_AddNodeAttribute)
        self.gridLayout_6.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.tblEdgeAttributes = QtWidgets.QTableWidget(self.tabWidgetPage3)
        self.tblEdgeAttributes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblEdgeAttributes.setAlternatingRowColors(True)
        self.tblEdgeAttributes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblEdgeAttributes.setObjectName("tblEdgeAttributes")
        self.tblEdgeAttributes.setColumnCount(2)
        self.tblEdgeAttributes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblEdgeAttributes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblEdgeAttributes.setHorizontalHeaderItem(1, item)
        self.tblEdgeAttributes.horizontalHeader().setVisible(True)
        self.tblEdgeAttributes.horizontalHeader().setCascadingSectionResizes(False)
        self.tblEdgeAttributes.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_6.addWidget(self.tblEdgeAttributes, 3, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/themes/default/propertyicons/attributes.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tabWidgetPage3, icon2, "")
        self.tabWidgetPage4 = QtWidgets.QWidget()
        self.tabWidgetPage4.setObjectName("tabWidgetPage4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tabWidgetPage4)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabWidgetPage4)
        self.scrollArea_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 616, 283))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.indexGroupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.indexGroupBox.setObjectName("indexGroupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.indexGroupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pbnChangeSpatialRefSys = QtWidgets.QPushButton(self.indexGroupBox)
        self.pbnChangeSpatialRefSys.setObjectName("pbnChangeSpatialRefSys")
        self.gridLayout_2.addWidget(self.pbnChangeSpatialRefSys, 0, 2, 1, 1)
        self.leSpatialRefSys = QtWidgets.QLineEdit(self.indexGroupBox)
        self.leSpatialRefSys.setReadOnly(True)
        self.leSpatialRefSys.setObjectName("leSpatialRefSys")
        self.gridLayout_2.addWidget(self.leSpatialRefSys, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.indexGroupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.indexGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.leLayerSource = QtWidgets.QLineEdit(self.indexGroupBox)
        self.leLayerSource.setEnabled(True)
        self.leLayerSource.setReadOnly(True)
        self.leLayerSource.setObjectName("leLayerSource")
        self.gridLayout_2.addWidget(self.leLayerSource, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.indexGroupBox, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/themes/default/propertyicons/general.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tabWidgetPage4, icon3, "")
        self.tabWidgetPage5 = QtWidgets.QWidget()
        self.tabWidgetPage5.setObjectName("tabWidgetPage5")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tabWidgetPage5)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.scrollArea = QtWidgets.QScrollArea(self.tabWidgetPage5)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 598, 265))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mLayerTitleLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.mLayerTitleLabel.setObjectName("mLayerTitleLabel")
        self.verticalLayout_2.addWidget(self.mLayerTitleLabel)
        self.mLayerTitleLineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.mLayerTitleLineEdit.setObjectName("mLayerTitleLineEdit")
        self.verticalLayout_2.addWidget(self.mLayerTitleLineEdit)
        self.mLayerAbstractLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mLayerAbstractLabel.sizePolicy().hasHeightForWidth())
        self.mLayerAbstractLabel.setSizePolicy(sizePolicy)
        self.mLayerAbstractLabel.setObjectName("mLayerAbstractLabel")
        self.verticalLayout_2.addWidget(self.mLayerAbstractLabel)
        self.mLayerAbstractTextEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.mLayerAbstractTextEdit.setMinimumSize(QtCore.QSize(0, 100))
        self.mLayerAbstractTextEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.mLayerAbstractTextEdit.setObjectName("mLayerAbstractTextEdit")
        self.verticalLayout_2.addWidget(self.mLayerAbstractTextEdit)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_15.addWidget(self.scrollArea, 0, 0, 1, 1)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/themes/default/propertyicons/metadata.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tabWidgetPage5, icon4, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(GraphAnalysisRendererGuiBase)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(GraphAnalysisRendererGuiBase)
        self.tabWidget_2.setCurrentIndex(0)
        self.buttonBox.accepted.connect(GraphAnalysisRendererGuiBase.accept)
        self.buttonBox.rejected.connect(GraphAnalysisRendererGuiBase.reject)
        QtCore.QMetaObject.connectSlotsByName(GraphAnalysisRendererGuiBase)

    def retranslateUi(self, GraphAnalysisRendererGuiBase):
        _translate = QtCore.QCoreApplication.translate
        GraphAnalysisRendererGuiBase.setWindowTitle(_translate("GraphAnalysisRendererGuiBase", "Graph Layer Properties"))
        self.lblTransparencyPercent.setText(_translate("GraphAnalysisRendererGuiBase", "Transparency"))
        self.legendtypelabel.setText(_translate("GraphAnalysisRendererGuiBase", "Graphical property"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage1), _translate("GraphAnalysisRendererGuiBase", "Style"))
        self.labelCheckBox.setText(_translate("GraphAnalysisRendererGuiBase", "Display labels"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage2), _translate("GraphAnalysisRendererGuiBase", "Labels"))
        self.label_6.setText(_translate("GraphAnalysisRendererGuiBase", "Nodes attributes"))
        self.tblNodeAttributes.setSortingEnabled(False)
        self.label_7.setText(_translate("GraphAnalysisRendererGuiBase", "Edges attributes"))
        self.pushButton_AddEdgeAttribute.setText(_translate("GraphAnalysisRendererGuiBase", "Add Edge Attribute"))
        self.pushButton_AddNodeAttribute.setText(_translate("GraphAnalysisRendererGuiBase", "Add Node Attribute"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage3), _translate("GraphAnalysisRendererGuiBase", "Fields"))
        self.indexGroupBox.setTitle(_translate("GraphAnalysisRendererGuiBase", "Options"))
        self.pbnChangeSpatialRefSys.setToolTip(_translate("GraphAnalysisRendererGuiBase", "Specify the coordinate reference system of the layer\'s geometry."))
        self.pbnChangeSpatialRefSys.setWhatsThis(_translate("GraphAnalysisRendererGuiBase", "Specify the coordinate reference system of the layer\'s geometry."))
        self.pbnChangeSpatialRefSys.setText(_translate("GraphAnalysisRendererGuiBase", "Specify CRS"))
        self.label_8.setText(_translate("GraphAnalysisRendererGuiBase", "CRS"))
        self.label_9.setText(_translate("GraphAnalysisRendererGuiBase", "Layer source"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage4), _translate("GraphAnalysisRendererGuiBase", "General"))
        self.mLayerTitleLabel.setText(_translate("GraphAnalysisRendererGuiBase", "Title"))
        self.mLayerAbstractLabel.setText(_translate("GraphAnalysisRendererGuiBase", "Abstract"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tabWidgetPage5), _translate("GraphAnalysisRendererGuiBase", "Metadata"))
        item = self.tblNodeAttributes.horizontalHeaderItem(0)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "Name"))
        item = self.tblNodeAttributes.horizontalHeaderItem(1)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "Type"))
        item = self.tblEdgeAttributes.horizontalHeaderItem(0)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "Name"))
        item = self.tblEdgeAttributes.horizontalHeaderItem(1)
        item.setText(_translate("GraphAnalysisDockWidgetBase", "Type"))
